<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SIPSorcery" Version="10.0.16" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\RemoteDesktop.Core\RemoteDesktop.Core.csproj" />
    <ProjectReference Include="..\..\Protocol\RemoteDesktop.Protocol\RemoteDesktop.Protocol.csproj" />
  </ItemGroup>

</Project>
